package com.medisync.notification;

public enum NotificationType {
    // PATIENT / CONSULTATION
    APPOINTMENT_ACCEPTED,
    APPOINTMENT_REJECTED,
    CONSULTATION_CANCELLED,
    CONSULTATION_STARTED,

    // CHAT
    NEW_CHAT_MESSAGE,
    NEW_CHAT_ATTACHMENT,

    // PRESCRIPTION / PAYMENT
    PRESCRIPTION_ISSUED,
    PRESCRIPTION_CANCELLED,
    PAYMENT_CONFIRMED,
    PRESCRIPTION_DISPENSED,

    // DOCTOR
    NEW_APPOINTMENT_REQUEST,
    PATIENT_CANCELLED_APPOINTMENT,

    // PROFESSIONAL VERIFICATION
    VERIFICATION_APPROVED,
    VERIFICATION_REJECTED,

    // ADMIN
    DOCTOR_VERIFICATION_SUBMITTED,
    DOCTOR_VERIFICATION_RESUBMITTED,
    PHARMACIST_VERIFICATION_SUBMITTED,
    PHARMACIST_VERIFICATION_RESUBMITTED
}
